### ISSUE TITLE
Pi mit Pixhawk verbinden

### ISSUE THREAD

**Issue by domhel** [dippa-1/autonomous-drone#4]

**Comment by domhel** [comment]
## Problem
- Pi kann den Port zur Drohne öffnen
- keine Daten werden empfangen
- Liegt es an Ubuntu?
	- Mit Raspberry Pi OS prüfen, ob Daten ankommen
	- Wenn Daten ankommen, liegt es an Ubuntu, sonst am Pixhawk
		- Pixhawk? PX4 neu installieren
		- Ubuntu? Schmerzen erleiden . . . weitere Suche

## Python Testprogramm
```python
import serial

with serial.Serial('/dev/ttyAMA0') as ser:
    print("port opened")
    ser.write("hello\n".encode('ascii'))
    while True:
        x = ser.readline()
        print(x)
```

## Referenzen
- [Question: Recommended way to run MAVSDK-Python on Raspberry Pi? · Issue #285 · mavlink/MAVSDK-Python (github.com)](https://github.com/mavlink/MAVSDK-Python/issues/285)

**Comment by et19021** [comment]
Problem gelöst, durch installation von MAVSDK auf Betribssystem Raspberrypi OS
Installationsschritte:
[MAVSDKGuide](https://mavsdk.mavlink.io/main/en/python/quickstart.html)

1.	MAVSDK installieren
pip3 install mavsdk

2.	Zum Testen asynchrone Pythen console installieren
pip3 install aioconsole

3.	Die installation erfolgt in einem Verzeichnis, welches nicht zu PATH gehört. Deshalb noch zu PATH zuweisen
export PATH="/home/ubuntu/.local/bin:$PATH"
4.	Es kommt ein Fehler beim Ausführen von
await drone.connect(system_address="serial:///dev/serial0:921600")
5.	Die Lösung für das Problem ist es grcio.toolls downgraden mit 
pip install grpcio-tools==1.43.0

Zum Testen ob die Kommunikation grundsätzlich funktioniert: 

1. apython console starten:
 apython
2. MAVSDK importieren 
from mavsdk import System
3. System Object kreieren und mit Drohne verbinden
drone = System()
await drone.connect()
4. Drohne Starten zum Test 
await drone.action.arm()
Die Rotoren sollte sich jetzt drehen

**Comment by et19021** [comment]
Verbindung zum Pixhawk über Serielle Schnittstelle GPIO des Pi ist hergestellt und getestet
